<<<<<<< HEAD
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const config = {
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	minify: prod,
	keepNames: true,
	metafile: prod,
	outfile: 'main.js',
	define: {
		'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
	},
	drop: prod ? ['console', 'debugger'] : [],
	legalComments: 'none',
	charset: 'utf8',
};

try {
	const context = await esbuild.context(config);

	if (prod) {
		console.log('🚀 Building for production...');
		const result = await context.rebuild();
		
		if (result.metafile) {
			console.log('\n📊 Build Analysis:');
			const analysis = await esbuild.analyzeMetafile(result.metafile);
			console.log(analysis);
		}
		
		console.log('✅ Production build completed successfully!');
		process.exit(0);
	} else {
		console.log('🔧 Starting development build with watch mode...');
		await context.watch();
		console.log('👀 Watching for changes...');
	}
} catch (error) {
	console.error('❌ Build failed:', error);
	process.exit(1);
}
=======
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
} 
>>>>>>> 0885c94521e11983aa8e85e3382c3b5efacbd10e
